# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: MSBuild

on:
  push:
    branches: [ "test" ]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: D:\a\1

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  #BUILD_CONFIGURATION: Release

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    #- uses: actions/checkout@v4

    - name: unzip
      run: |
           New-Item -ItemType Directory -Path "D:\a\1"
           Invoke-WebRequest -Uri "https://github.com/x500x/zip_unzipTest/blob/main/unzip.exe" -OutFile "D:\a\unzip.exe"
           Invoke-WebRequest -Uri "https://github.com/x500x/workflowtest1/blob/main/Detours-main.zip" -OutFile "D:\a\1.zip"
           D:\a\unzip.exe -o 1.zip -d ${{env.GITHUB_WORKSPACE}}
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}
    
    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference 
      run: |
           msbuild /m /p:Configuration=Release   #x64 ${{env.SOLUTION_FILE_PATH}}
           msbuild /m /p:Configuration=Release /p:platform=x86 ${{env.SOLUTION_FILE_PATH}}  #x86
    - name: upload__artifact
      uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
      with:
       path: ${{env.SOLUTION_FILE_PATH}}
